# Generated by Django 5.1.3 on 2024-11-29 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, default=0, unique=True)),
                ('position', models.CharField(choices=[('GK', 'Portero'), ('DF', 'Defensa'), ('MD', 'Centrocampista'), ('FW', 'Delantero')], default='MD', max_length=2)),
                ('played', models.SmallIntegerField(default=0)),
                ('goals', models.SmallIntegerField(default=0)),
                ('assists', models.SmallIntegerField(default=0)),
                ('yellow_cards', models.SmallIntegerField(default=0)),
                ('red_cards', models.SmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
