# Generated by Django 5.1.3 on 2024-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_options_player_birthdate_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(default='🇪🇸', max_length=20),
        ),
    ]
