# Generated by Django 5.1.3 on 2024-11-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_team_club_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_goals', models.SmallIntegerField(blank=True, null=True)),
                ('away_goals', models.SmallIntegerField(blank=True, null=True)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournament.team')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_matches', to='tournament.team')),
            ],
        ),
    ]
