# Generated by Django 5.1.3 on 2024-11-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
    ]
