# Generated by Django 5.1.3 on 2024-11-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_user'),
        ('tournament', '0005_alter_match_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.SmallIntegerField(default=0)),
                ('position', models.CharField(choices=[('GL', 'Gol'), ('CG', 'Cambio'), ('YC', 'Tarjeta Amarilla'), ('RC', 'Tarjeta Roja')], default='GL', max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournament.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='players.player')),
                ('second_player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_events', to='players.player')),
            ],
        ),
    ]
