# Generated by Django 5.1.3 on 2024-11-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['minute']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='position',
            new_name='type',
        ),
    ]
