# Generated by Django 5.1.3 on 2024-11-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_user'),
        ('tournament', '0007_alter_event_options_rename_position_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='second_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_events', to='players.player'),
        ),
    ]
