# Generated by Django 5.1.3 on 2024-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_event_second_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='local_goals',
            field=models.SmallIntegerField(default=0),
        ),
    ]
