# Generated by Django 5.1.3 on 2024-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_match_away_goals_alter_match_local_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('GL', 'Gol'), ('OG', 'Autogol'), ('CG', 'Cambio'), ('YC', 'Tarjeta Amarilla'), ('RC', 'Tarjeta Roja')], default='GL', max_length=2),
        ),
    ]
