# Generated by Django 5.1.3 on 2024-12-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_event_game_alter_event_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='local',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
