# Generated by Django 5.1.3 on 2024-12-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_remove_match_away_remove_match_local_delete_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='info',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
