# Generated by Django 5.1.3 on 2024-12-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_team_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='info',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
