# Generated by Django 5.1.3 on 2024-12-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_team_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='shield',
            field=models.ImageField(default='shields/default.png', upload_to='shields'),
        ),
    ]
