# Generated by Django 5.1.3 on 2024-12-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_clasification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasification',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clasification', to='tournament.team'),
        ),
    ]
