# Generated by Django 5.1.3 on 2024-12-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_alter_clasification_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasification',
            options={'ordering': ['-points', '-goals_difference', '-team', '-played']},
        ),
    ]
