# Generated by Django 5.1.3 on 2024-12-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_alter_clasification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasification',
            options={'ordering': ['-points', '-goals_difference', '-played', '-team']},
        ),
    ]
