# Generated by Django 5.1.3 on 2025-01-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_alter_clasification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasification',
            options={'ordering': ['-points', '-played']},
        ),
    ]
