# Generated by Django 5.1.3 on 2024-12-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0005_alter_player_options'),
        ('tournament', '0010_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_goals', models.SmallIntegerField(default=0)),
                ('away_goals', models.SmallIntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='tournament.team')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_games', to='tournament.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.SmallIntegerField(default=0)),
                ('type', models.CharField(choices=[('GL', 'Gol'), ('OG', 'Autogol'), ('CG', 'Cambio'), ('YC', 'Tarjeta Amarilla'), ('RC', 'Tarjeta Roja')], default='GL', max_length=2)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='players.player')),
                ('second_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_events', to='players.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.game')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
    ]
