# Generated by Django 5.1.3 on 2024-12-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='played',
        ),
    ]
