# Generated by Django 5.1.3 on 2024-12-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('GL', 'Gol'), ('OG', 'Autogol'), ('PG', 'Gol de penalti'), ('CG', 'Cambio'), ('YC', 'Tarjeta Amarilla'), ('RC', 'Tarjeta Roja')], default='GL', max_length=2),
        ),
    ]
