# Generated by Django 5.1.3 on 2024-12-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_league_game',
            field=models.BooleanField(default=False),
        ),
    ]
