# Generated by Django 5.1.3 on 2024-12-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_goals',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='local_goals',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
