# Generated by Django 5.1.3 on 2024-12-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_away_goals_alter_game_local_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_goals',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='local_goals',
            field=models.SmallIntegerField(default=0),
        ),
    ]
