# Generated by Django 5.1.3 on 2024-12-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_away_goals_alter_game_local_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('T', 'Pendiente'), ('I', 'En juego'), ('F', 'Finalizado')], default='T', max_length=1),
        ),
    ]
