# Generated by Django 5.1.3 on 2025-01-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_league_game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
    ]
