# Generated by Django 5.1.3 on 2025-01-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_remove_game_is_league_game_remove_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pointed',
            field=models.BooleanField(default=False),
        ),
    ]
